version: "3.9"

services:
  db:
    image: mysql:5.7
    container_name: wp_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: Admin_123456
      MYSQL_ROOT_PASSWORD: Admin_123456
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    container_name: wp_app
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: Admin_123456
    volumes:
      - ./plugin:/var/www/html/wp-content/plugins
      - ./uploads:/var/www/html/wp-content/uploads

volumes:
  db_data: